package vn.ticketscenter.fulfillment.controller;
import jakarta.persistence.*;import jakarta.servlet.annotation.WebServlet;import jakarta.servlet.http.*;import vn.ticketscenter.config.persistence.*;import vn.ticketscenter.config.web.*;import vn.ticketscenter.fulfillment.dto.FulfillmentDtos.*;import vn.ticketscenter.fulfillment.repository.OperationsRepository;import vn.ticketscenter.fulfillment.service.OperationsService;import vn.ticketscenter.identity.filter.AuthenticationFilter;import vn.ticketscenter.identity.service.AccountService.AuthenticatedAccount;import java.io.*;import java.util.*;import java.util.regex.*;
@WebServlet(name="OperationsServlet",urlPatterns={"/api/check-ins","/api/refund-requests","/api/admin/refund-requests/*"})
public final class OperationsServlet extends HttpServlet{
 private final OperationsService service;public OperationsServlet(){service=null;} OperationsServlet(OperationsService s){service=s;}
 protected void doPost(HttpServletRequest req,HttpServletResponse res)throws IOException{AuthenticatedAccount a=account(req,res);if(a==null)return;OperationsService s=resolve(req,res);if(s==null)return;try{Map<String,String>b=JsonObjectParser.parse(req.getReader());String path=req.getPathInfo();String servlet=req.getServletPath();if(servlet.equals("/api/check-ins")){var r=s.checkIn(a,uuid(b.get("eventId")),b.get("ticketCode"));HttpResponses.data(res,"{\"result\":"+HttpResponses.jsonString(r.result())+",\"ticketId\":"+(r.ticketId()==null?"null":HttpResponses.jsonString(r.ticketId().toString()))+",\"scannedAt\":"+HttpResponses.jsonString(r.scannedAt().toString())+"}");return;}if(servlet.equals("/api/refund-requests")){List<UUID>ids=new ArrayList<>();Matcher m=Pattern.compile("[0-9a-fA-F-]{36}").matcher(b.getOrDefault("ticketIds",""));while(m.find())ids.add(uuid(m.group()));var r=s.request(a,uuid(b.get("orderId")),ids,b.get("reason"));HttpResponses.data(res,"{\"requestId\":"+HttpResponses.jsonString(r.requestId().toString())+",\"requestedAmount\":"+HttpResponses.jsonString(r.requestedAmount().toString())+"}");return;}if(servlet.equals("/api/admin/refund-requests")){var id=uuid(path.substring(1,path.length()-9));String out=s.decide(a,id,b.get("decision"),b.get("rejectionReason"));HttpResponses.data(res,"{\"decision\":"+HttpResponses.jsonString(out)+"}");return;}HttpResponses.error(res,404,"NOT_FOUND","Endpoint không tồn tại");}catch(SecurityException e){HttpResponses.error(res,403,"FORBIDDEN",e.getMessage());}catch(RuntimeException e){error(res,e);}}
 private OperationsService resolve(HttpServletRequest r,HttpServletResponse p)throws IOException{if(service!=null)return service;Object x=r.getServletContext().getAttribute(PersistenceListener.REGISTRY_ATTRIBUTE);if(x instanceof PersistenceRegistry z)return new OperationsService(z.transactionManager(),new OperationsRepository());HttpResponses.error(p,503,"DEPENDENCY_UNAVAILABLE","Operations service unavailable");return null;}
 private static AuthenticatedAccount account(HttpServletRequest r,HttpServletResponse p)throws IOException{Object x=r.getAttribute(AuthenticationFilter.ACCOUNT_ATTRIBUTE);if(x instanceof AuthenticatedAccount a)return a;HttpResponses.error(p,401,"UNAUTHORIZED","Yêu cầu đăng nhập");return null;}
 private static UUID uuid(String s){try{return UUID.fromString(s);}catch(Exception e){throw new IllegalArgumentException("id không hợp lệ");}}
 private static String refunds(List<RefundableTicket>v){return v.stream().map(x->"{\"ticketId\":"+HttpResponses.jsonString(x.ticketId().toString())+",\"paidAmount\":"+HttpResponses.jsonString(x.paidAmount().toString())+",\"zoneName\":"+HttpResponses.jsonString(x.zoneName())+",\"seatLabel\":"+(x.seatLabel()==null?"null":HttpResponses.jsonString(x.seatLabel()))+"}").reduce((a,b)->a+","+b).map(x->"["+x+"]").orElse("[]");}
 private static void error(HttpServletResponse r,RuntimeException e)throws IOException{HttpResponses.error(r,e instanceof NoSuchElementException?404:409,"REQUEST_FAILED",e.getMessage());}
}
